### ISSUE TITLE
Auth review 

### ISSUE THREAD

**Issue by remm9** [remm9/FoxeoFullstockProject#4]
most of links on the home page are not functional, case i have not build the functionality yet. the splash page and auth should be good.

**Comment by kkossally** [comment]
Overall, this is very solid. To make it even better, tackle the following tasks:

- [ ] address the 404 error in the console on page load

- [ ] review the text on the splash and fix typos and spelling mistakes

- [ ] remove the built in focus effect on the user dropdown menu and other clickable elements (did you write a CSS reset?)

- [ ] make sure to account for different screen sizes, everything is off center on my monitor

- [ ] style the footer to match Vimeo

Feel free to leave comments on this issue if you have questions. Make sure to Slack me if you do so to make sure that I see them in a timely fashion.

**Comment by remm9** [comment]
all changes implemented
